language: python
python: 2.7
sudo: false
cache:
  directories:
    - eggs
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
  - PLONE_VERSION=5.2
matrix:
  fast_finish: true
install:
  - sed -ie "s#test-5.0#test-$PLONE_VERSION#" buildout.cfg
  - python bootstrap.py
  - bin/buildout annotate
  - bin/buildout
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls

notifications:
  email:
    - t_schorr@gmx.de
