dist: bionic
language: python
python: 2.7
sudo: false
cache:
  pip: true
  directories:
    - eggs
matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env: PLONE_VERSION="4.3"
    - python: "2.7"
      env: PLONE_VERSION="5.1"
    - python: "2.7"
      env: PLONE_VERSION="5.2"
    - python: "3.7"
      env: PLONE_VERSION="5.2"
before_install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - sed -ie "s#5.2-latest#$PLONE_VERSION-latest#" buildout.cfg
  - bin/buildout -N annotate
install:
  - bin/buildout -N install test createcoverage
script:
  - bin/test
after_success:
  - bin/createcoverage -d htmlcov
  - pip install coveralls
  - coveralls
notifications:
  email:
    - t_schorr@gmx.de
